name: Publish to FlakeHub

on:
  push:
    branches: [main]
    paths: ["**.nix", "**.rs", "Cargo.lock"]
  pull_request:
    paths: ["**.nix", "**.rs", "Cargo.lock"]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    permissions:
      id-token: write
      contents: read

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup cachix
        uses: cachix/cachix-action@v15
        with:
          name: catppuccin
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Flake check
        run: nix flake check -Lv

      - name: Build packages
        run: nix build -L .#catwalk

      - uses: DeterminateSystems/flakehub-push@main
        # only push to FlakeHub once when running on main
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request' && matrix.os == 'ubuntu-latest'
        with:
          name: catppuccin/toolbox
          rolling: true
          visibility: public
